name: iOS CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Xcode 16.0
        run: |
          sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer

      - name: Install Dependencies
        run: |
          cd uusr || { echo "Directory 'uusr' not found!"; exit 1; }
          xcodebuild -resolvePackageDependencies

      - name: Build App
        run: |
          cd uusr || { echo "Directory 'uusr' not found!"; exit 1; }
          xcodebuild -scheme uusr -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 16' build

      - name: Run Tests
        run: |
          cd uusr || { echo "Directory 'uusr' not found!"; exit 1; }
          xcodebuild test -scheme uusr -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 16'
