name: iOS CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Xcode 16.0
        run: |
          sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer

      - name: Install Dependencies
        run: |
          cd uusr || { echo "Directory 'uusr' not found!"; exit 1; }
          xcodebuild -resolvePackageDependencies
      - name: List Available Simulators
        run: xcrun simctl list
        
      - name: Build App
        run: |
          cd uusr || { echo "Directory 'uusr' not found!"; exit 1; }
          xcodebuild -scheme uusr -destination 'platform=iOS Simulator,OS=18.1,name=iPhone 16' build

  unit-tests:
    name: Run Unit Tests
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Xcode 16.0
        run: |
          sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
      - name: List Available Simulators
        run: xcrun simctl list

      - name: Run Unit Tests
        run: |
          cd uusr || { echo "Directory 'uusr' not found!"; exit 1; }
          xcodebuild test -scheme uusr -destination 'platform=iOS Simulator,OS=18.1,name=iPhone 16' -only-testing:uusrTests

  ui-tests:
    name: Run UI Tests
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Xcode 16.0
        run: |
          sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
      - name: List Available Simulators
        run: xcrun simctl list

      - name: Boot Simulator
        run: |
          xcrun simctl boot "iPhone 16" || echo "Simulator already booted"
          sleep 60 # Increase the time to let the simulator fully boot
          
      - name: Boot Simulator
        run: |
          xcrun simctl boot "iPhone 16" || echo "Simulator already booted"
          sleep 30 # Give the simulator some time to fully boot

      - name: Run UI Tests
        run: |
          cd uusr || { echo "Directory 'uusr' not found!"; exit 1; }
          xcodebuild test -scheme uusrUITests -destination 'platform=iOS Simulator,OS=18.1,name=iPhone 16'
        env:
          SIMCTL_CHILD_isHeadless: YES
